import { XmlPart } from "./package/xml-part.js";
import { Paragraph } from "./paragraph/paragraph.js";
import { NamedStyles } from "./text/named-styles.js";
import { Section } from "./section.js";
import { AbstractNumberings } from "./numbering/abstract-numberings.js";
import { Table } from "./table/table.js";
import { Relationships } from "./package/relationships.js";
import { Package } from "./package/package.js";
import { ILayoutable } from "./utils/i-layoutable.js";
import { VirtualFlow } from "./utils/virtual-flow.js";
export declare class DocumentX implements ILayoutable {
    private part;
    private pars;
    private _section;
    private _styles;
    private _numberings;
    private _rels;
    pack: Package;
    constructor(pack: Package, part: XmlPart);
    parseContent(): void;
    performLayout(flow: VirtualFlow): void;
    readonly relationships: Relationships | undefined;
    readonly styles: NamedStyles | undefined;
    readonly numberings: AbstractNumberings | undefined;
    setRelationships(relationships: Relationships): void;
    setNamedStyles(styles: NamedStyles): void;
    setNumberings(numberings: AbstractNumberings): void;
    readonly paragraphs: (Paragraph | Table)[];
    readonly section: Section | undefined;
}
