import { NamedStyles } from "./named-styles.js";
import { ParStyle, Justification } from "../paragraph/par-style.js";
import { RunStyle, UnderlineMode } from "./run-style.js";
import { InSequence } from "../utils/in-sequence.js";
import { TableStyle } from "../table/table-style.js";
export declare class Style {
    private _basedOn;
    private _basedOnId;
    runStyle: RunStyle;
    parStyle: ParStyle;
    tableStyle: TableStyle | undefined;
    static fromStyleNode(styleNode: ChildNode): Style;
    static getShadingFromNode(styleNode: ChildNode): string | undefined;
    constructor(parStyle?: ParStyle, runStyle?: RunStyle);
    applyNamedStyles(namedStyles: NamedStyles | undefined): void;
    readonly italic: boolean;
    readonly bold: boolean;
    readonly underlineMode: UnderlineMode;
    readonly strike: boolean;
    readonly doubleStrike: boolean;
    readonly fontFamily: string;
    readonly fontSize: number;
    readonly charSpacing: number;
    readonly charStretch: number;
    readonly lineSpacing: number;
    readonly shadingColor: string;
    getIndentation(inRun: InSequence, inParagaph: InSequence): number;
    readonly caps: boolean;
    readonly smallCaps: boolean;
    readonly color: string;
    readonly justification: Justification;
    readonly invisible: boolean;
    readonly font: string;
    toString(): string;
    private getValue;
    private getRecursive;
}
